#if !canImport(ObjectiveC)
import XCTest

extension DataTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DataTests = [
        ("testCaseCompletedParser", testCaseCompletedParser),
        ("testCaseStartedParser", testCaseStartedParser),
        ("testSuiteCompletedParser", testSuiteCompletedParser),
        ("testSuiteStartedParser", testSuiteStartedParser),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(DataTests.__allTests__DataTests),
    ]
}
#endif
